const CinemaListingImg = [
  {
    id: 1,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 2,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem psum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ipsum lorem ipsum lorem ippsum lorem ip psum lorem ipsum lorem ipsum lorem ip psum lorem ipsum lorem ipsum lorem ipipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 3,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 4,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 5,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 6,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 7,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 8,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 9,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 10,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 11,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 12,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 13,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 14,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 15,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 16,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 17,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 18,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 19,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 20,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 21,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 22,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 23,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 24,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 25,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 26,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 27,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 28,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 29,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 30,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 31,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
  {
    id: 32,
    src: '',
    alt: 'pic one',
    title: 'Loren Ipsum lorem ipsum loren ip',
    year: '2020',
    filmDuration: '140 min',
    filmType: 'Movie',
    quality: 'HD',
    description:
      'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  lorem ipsum vlorem ipsulorem Ipsum',
    rating: '6.1',
    country: 'France',
    genre: 'Comedy',
  },
];
export default CinemaListingImg;
